#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "onedark"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    filetree_direction = "left"
    filemanager = "nerdtree"
    enable_ycm = false
    autocomplete_method = "completor"
    bootstrap_before = "custom_init#before"
    # enable / disable relative number in vim got code line numbers
    relativenumber= false

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
 auto_completion_return_key_behavior = "complete"
# auto_completion_tab_key_behavior = "smart"


[[layers]]
name = 'shell'
# default_shell = "VimShell"
default_position = 'bottom'
default_height = 30

[[layers]]
  name = "lang#python"
  python_file_head = [
      '#!/usr/bin/env python3',
      '# -*- coding: utf-8 -*-',
      '',
      ''
  ]

  [[layers]]
  name = "colorscheme"

[[layers]]
  name = "git"

[[layers]]
  name = "lang#sh"

[[layers]]
    name = 'core'
    filetree_show_hidden = true

[[layers]]
  name = "lang#javascript"

[[custom_plugins]]
  name = "hashivim/vim-terraform"
  merged = false
  
  [[custom_plugins]]
    name = "tpope/vim-surround"
    merged = false
